### ISSUE TITLE
fflib_InvocationOnMock is failing

### ISSUE THREAD

**Issue by dieffrei** [financialforcedev/fflib-apex-mocks#46]
Today all apex mocks tests on fflib_AnswerTest is failing; Any help?
![captura de tela 2017-08-03 11 24 41](https://user-images.githubusercontent.com/3090010/28915120-631762d8-783e-11e7-965c-801d2509a206.png)

**Comment by XoNoX79** [comment]
Hi, I had a look to that. For some reason the stubbed list created with the
stub API is null. I'm investigating further since I had the same problem.
I'll keep you updated,
Enzo

**Comment by dieffrei** [comment]
Yeap, I tried to install ApexMocks in a new developer org and it is working.
I made a System.debug on line 68 and it is null, may a salesforce issue?
![captura de tela 2017-08-03 12 45 15](https://user-images.githubusercontent.com/3090010/28918457-9c1972dc-7849-11e7-8320-40a67aef77e3.png)

**Comment by ImJohnMDaniel** [comment]
I, too, have this issue.  It started yesterday for me.  It has nothing to do with ApexMocks and is a platform bug.  It is like @XoNoX79 said - The Test.createStub() method started returning null.  This issue is only affecting certain orgs.  I have some sandboxes affected and some are not (thankfully, my production org is not affected).  It also does not appear to be "pod specific"; I have some on CS14 affected and others on CS14 are running fine.  I opened a support case with Salesforce yesterday and it wen to Tier 3 quickly.

FYI - @afawcett , @phardaker, @frup42

**Comment by dieffrei** [comment]
We are on "go live" and have been affecting our production org.

**Comment by bhavaankura** [comment]
We are also experiencing this issue. It started happening with our last nightly production build.

**Comment by tfuda** [comment]
Not to jump on the "me too" bandwagon, but I just observed this on my NA50 org about an hour ago. I swear the tests ran successfully earlier today. Yay Salesforce.

**Comment by dieffrei** [comment]
R&D team have already working on a resolution, but there is not a delivery forecast

**Comment by ImJohnMDaniel** [comment]
Salesforce Support has opened a "known issue" on this.  

https://success.salesforce.com/issues_view?id=a1p3A0000001D19

I was told to expect a fix to be deployed to all affected orgs within the next 18-24 hours.

**Comment by frup42** [comment]
Going to close on the grounds that there's nothing for us to do, but sit back and wait.
