### ISSUE TITLE
Functionality for mocking method call to alter mutable parameters

### ISSUE THREAD

**Issue by donnie745** [financialforcedev/fflib-apex-mocks#71]
Hi there,
I have an interface with a method that applies changes to mutable parameters and as far as I can tell the fflib library does not provide the functionality to setup the mock instance in the unit test to apply changes to the input parameters.

If this is indeed not currently available, are there any plans to add this in future? It would be a very useful addition to the library.

Cheers,
Donnie

**Comment by donnie745** [comment]
Just to give some background, my use case is I have a Metadata access layer interface which will retrieve __mdt records for any custom metadata type. To avoid clients having to extract elements from a returned List<SObject> and cast to the metadata type the interface makes the clients pass an empty List<SObject> (the list instance being of the underlying metadata type) and this list is populated within the method with the method using the List<SObject> method getSObjectType() to determine the underlying metadata type. As Salesforce don't provide generics this was the only workaround possible without forcing clients to implement list copying and casting to get a List of the underlying metadata type.

I could change the interface to return a List<SObject> to get round this but I really don't like making the clients do the ugly work of building up a new list of the underlying type casting each element to the metadata type on adding to the new list each time they want to use this interface.

**Comment by dfruddffdc** [comment]
It supports Answering, see more detail here: https://xonoxforce.wordpress.com/2017/03/31/answering-with-apex-mocks/

Usually you just stub methods so that they return a particular value or throw a particular exception when invoked with the specified set of arguments. But as you've found, there are methods whose job is to mutate the supplied arguments.

Answering allows you to provide your own dummy implementation of these methods, to do things such as:
* mutate supplied arguments
* use the supplied arguments to derive a return value (e.g. return the supplied String argument, but in upper-case)

So answers are very powerful, just take care to keep your tests naive and self-contained - avoid simply recreating the actual implementation, since we're using mocking to avoid coupling with the real method.

**Comment by donnie745** [comment]
Thanks for getting back so quickly. I'll need to update our version of the fflib library (and merge in a couple of bug fixes applied to the old library our end for the issue raised in https://github.com/financialforcedev/fflib-apex-mocks/issues/30 and the issue raised in https://github.com/financialforcedev/fflib-apex-mocks/issues/29, although it looks like the second issue may have also been fixed by you in https://github.com/financialforcedev/fflib-apex-mocks/pull/42), as we don't have the fflib_Answer class and functionality in our current version.

Cheers,
Donnie
